### ISSUE TITLE
Kubernetes configmap change leads to failed to open stream

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon#164]
#### Description
**Is**:
`
<br />
<b>Warning</b>:  file_get_contents(/usr/share/balloon/config/config.yaml): failed to open stream: No such file or directory in <b>/usr/share/balloon/vendor/hassankhan/config/src/FileParser/Yaml.php</b> on line <b>29</b><br />
<br />
<b>Fatal error</b>:  Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at /usr/share/balloon/vendor/hassankhan/config/src/FileParser/Yaml.php:29) in /usr/share/balloon/vendor/gyselroth/micro-http/src/Response.php:119
Stack trace:
#0 [internal function]: Balloon\Bootstrap\AbstractBootstrap-&gt;Balloon\Bootstrap\{closure}(2, 'Cannot modify h...', '/usr/share/ball...', 119, Array)
#1 /usr/share/balloon/vendor/gyselroth/micro-http/src/Response.php(119): header('Content-Type: a...')
#2 /usr/share/balloon/vendor/gyselroth/micro-http/src/Response.php(183): Micro\Http\Response-&gt;sendHeaders()
#3 /usr/share/balloon/src/lib/Bootstrap/Http.php(147): Micro\Http\Response-&gt;send()
#4 [internal function]: Balloon\Bootstrap\Http-&gt;Balloon\Bootstrap\{closure}(Object(ErrorException))
#5 {main}
  thrown in <b>/usr/share/balloon/vendor/gyselroth/micro-http/src/Response.php</b> on line <b>119</b><br />
`
clearstatcache has been introduced in v2.0.9 but the error still persists.

**Should**:
No error after change.

#### balloon server version
2.0.10

**Comment by juckerf** [comment]
seems like opcache joined the party...
if i add a `opcache_reset` in `src/lib/Bootstrap/ContainerBuilder.php` (see below) the config change is reflected immediately (Note: an `opcache_invalidate(__FILE__)` does not suffice...)
```
    44	opcache_reset(); file_put_contents("/tmp/log",time() . " - " . getmypid() . " - " . realpath($path) . " - " . __FILE__ . "\n",FILE_APPEND);
```

**Comment by raffis** [comment]
running `opcache_reset()` each request overturns the usage of opcache. Maybe we need to store the config in apc and load it from there if the file can not be opened but sounds fishy

**Comment by juckerf** [comment]
> running `opcache_reset()` each request overturns the usage of opcache
I'm aware of that... my last comment was merely to report my findings during debugging :wink:

**Comment by raffis** [comment]
https://pracucci.com/php-realpath-cache-and-kubernetes-secrets-configmap-updates.html

**Comment by raffis** [comment]
This will be solved with #338 since we will implement the http stack in balloon itself and moving away from a php-fpm/nginx construct.
