### ISSUE TITLE
Restore a collection with child nodes ends in exception could not restore node into a deleted parent

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon#258]
#### Description
**Is**:

Restore a collection with child nodes ends in exception:
```
2019-30-01 16:35:26 [Micro\Http\Router,ERROR]: uncaught exception could not restore node LICENSE into a deleted parent 5c50563328ba26019f6083a3]  [object] (Balloon\Filesystem\Exception\Conflict(code: 21): could not restore node LICENSE into a deleted parent 5c50563328ba26019f6083a3 at /srv/www/balloon/src/lib/Filesystem/Node/AbstractNode.php:600)
[stacktrace]
#0 /srv/www/balloon/src/lib/Filesystem/Node/AbstractNode.php(642): Balloon\Filesystem\Node\AbstractNode->undelete(0, '5c51d24ec4399', false)
#1 /srv/www/balloon/src/lib/Filesystem/Node/Collection.php(794): Balloon\Filesystem\Node\AbstractNode->Balloon\Filesystem\Node\{closure}(Object(Balloon\Filesystem\Node\File))
#2 /srv/www/balloon/src/lib/Filesystem/Node/AbstractNode.php(643): Balloon\Filesystem\Node\Collection->doRecursiveAction(Object(Closure), 1)
#3 /srv/www/balloon/src/app/Balloon.App.Api/v2/Nodes.php(190): Balloon\Filesystem\Node\AbstractNode->undelete(0)
#4 [internal function]: Balloon\App\Api\v2\Nodes->Balloon\App\Api\v2\{closure}(Object(Balloon\Filesystem\Node\Collection))
#5 /srv/www/balloon/src/app/Balloon.App.Api/Controller.php(195): Closure->call(Object(Balloon\App\Api\v2\Nodes), Object(Balloon\Filesystem\Node\Collection))
#6 /srv/www/balloon/src/app/Balloon.App.Api/v2/Nodes.php(197): Balloon\App\Api\Controller->bulk('5c50563328ba260...', NULL, Object(Closure))
#7 [internal function]: Balloon\App\Api\v2\Nodes->postUndelete('5c50563328ba260...', NULL, false, NULL, NULL, 0)
#8 /srv/www/balloon/vendor/gyselroth/micro-http/src/Router.php(246): call_user_func_array(Array, Array)
#9 /srv/www/balloon/src/lib/Bootstrap/Http.php(89): Micro\Http\Router->run()
#10 /srv/www/balloon/src/httpdocs/index.php(48): Balloon\Bootstrap\Http->process()
#11 {main}
```

**Should**:

**Comment by raffis** [comment]
https://github.com/php-cache/array-adapter/blob/master/ArrayCachePool.php#L128
