### ISSUE TITLE
Delta extremely slow with many nodes from inbox shares

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon#372]
#### Describe the bug
Get /api/v1/node/delta is incredibly slow if the delta contains many nodes from a inbox share.
It even runs into timeouts and lead to big loads on the MongoDB.

#### To Reproduce
1. Create inbox share and share for user 1 and user 2
2. Fetch delta as user 2, store cursor
3. Upload big folder with many files & sub folders into inbox share as user 1
4. Fetch delta as user 2 with cursor from 2.
5. Request may end in timeout or is incredibly slow (~30s)

#### Expected behavior
Fast as usual.

#### Environment
 - balloon server version: v2.6.4
 - Deployed as: docker
 - PHP version: not relevant
 - MongoDB version: v3.4.18

#### Additional context
```
#15 {main}
2019-28-08 10:56:01 [Balloon\Filesystem,ERROR]: remove node from result list, failed load node  [object] (Balloon\Filesystem\Acl\Exception\Forbidden(code: 40): not allowed to access node at /usr/share/balloon/src/lib/Filesystem.php:628)
[stacktrace]
#0 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, Object(Balloon\Filesystem\Node\Collection))
#1 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#2 /usr/share/balloon/src/lib/Filesystem.php(220): iterator_to_array(Object(Generator))
#3 /usr/share/balloon/src/lib/Filesystem.php(611): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#4 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, NULL)
#5 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#6 /usr/share/balloon/src/lib/Filesystem.php(220): iterator_to_array(Object(Generator))
#7 /usr/share/balloon/src/lib/Filesystem.php(611): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#8 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, NULL)
#9 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#10 /usr/share/balloon/src/lib/Filesystem.php(220): iterator_to_array(Object(Generator))
#11 /usr/share/balloon/src/lib/Filesystem.php(611): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#12 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, NULL)
#13 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#14 /usr/share/balloon/src/lib/Filesystem.php(220): iterator_to_array(Object(Generator))
#15 /usr/share/balloon/src/lib/Filesystem.php(611): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#16 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, NULL)
#17 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#18 /usr/share/balloon/src/lib/Filesystem.php(220): iterator_to_array(Object(Generator))
#19 /usr/share/balloon/src/lib/Filesystem.php(611): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#20 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, NULL)
#21 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#22 /usr/share/balloon/src/lib/Filesystem.php(220): iterator_to_array(Object(Generator))
#23 /usr/share/balloon/src/lib/Filesystem/Delta.php(441): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#24 /usr/share/balloon/src/lib/Filesystem/Delta.php(300): Balloon\Filesystem\Delta->getDeletedNodeDelta(Array)
#25 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8NTAwfDB...', 100, NULL)
#26 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8NTAwfDB...', 100, NULL)
#27 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8NDAwfDB...', 100, NULL)
#28 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8MzAwfDB...', 100, NULL)
#29 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8MjAwfDB...', 100, NULL)
#30 /usr/share/balloon/src/app/Balloon.App.Api/v1/Node.php(1014): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8MTAwfDB...', 100, NULL)
#31 [internal function]: Balloon\App\Api\v1\Node->getDelta(Object(Balloon\App\Api\v1\AttributeDecorator\DeltaDecorator), NULL, NULL, 'ZGVsdGF8MHwwfDV...', 100, Array)
#32 /usr/share/balloon/vendor/gyselroth/micro-http/src/Router.php(246): call_user_func_array(Array, Array)
#33 /usr/share/balloon/src/lib/Bootstrap/Http.php(91): Micro\Http\Router->run()
#34 /usr/share/balloon/bin/httpdocs/index.php(47): Balloon\Bootstrap\Http->process()
#35 {main}
2019-28-08 10:56:01 [Balloon\Filesystem,ERROR]: remove node from result list, failed load node  [object] (Balloon\Filesystem\Exception\NotFound(code: 49): node [5d5f91f930101d16bf550ef2] not found at /usr/share/balloon/src/lib/Filesystem.php:223)
[stacktrace]
#0 /usr/share/balloon/src/lib/Filesystem.php(611): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#1 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, NULL)
#2 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#3 /usr/share/balloon/src/lib/Filesystem.php(220): iterator_to_array(Object(Generator))
#4 /usr/share/balloon/src/lib/Filesystem.php(611): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#5 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, NULL)
#6 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#7 /usr/share/balloon/src/lib/Filesystem.php(220): iterator_to_array(Object(Generator))
#8 /usr/share/balloon/src/lib/Filesystem.php(611): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#9 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, NULL)
#10 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#11 /usr/share/balloon/src/lib/Filesystem.php(220): iterator_to_array(Object(Generator))
#12 /usr/share/balloon/src/lib/Filesystem.php(611): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#13 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, NULL)
#14 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#15 /usr/share/balloon/src/lib/Filesystem.php(220): iterator_to_array(Object(Generator))
#16 /usr/share/balloon/src/lib/Filesystem.php(611): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#17 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, NULL)
#18 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#19 /usr/share/balloon/src/lib/Filesystem.php(220): iterator_to_array(Object(Generator))
#20 /usr/share/balloon/src/lib/Filesystem/Delta.php(441): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#21 /usr/share/balloon/src/lib/Filesystem/Delta.php(300): Balloon\Filesystem\Delta->getDeletedNodeDelta(Array)
#22 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8NTAwfDB...', 100, NULL)
#23 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8NTAwfDB...', 100, NULL)
#24 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8NDAwfDB...', 100, NULL)
#25 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8MzAwfDB...', 100, NULL)
#26 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8MjAwfDB...', 100, NULL)
#27 /usr/share/balloon/src/app/Balloon.App.Api/v1/Node.php(1014): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8MTAwfDB...', 100, NULL)
#28 [internal function]: Balloon\App\Api\v1\Node->getDelta(Object(Balloon\App\Api\v1\AttributeDecorator\DeltaDecorator), NULL, NULL, 'ZGVsdGF8MHwwfDV...', 100, Array)
#29 /usr/share/balloon/vendor/gyselroth/micro-http/src/Router.php(246): call_user_func_array(Array, Array)
#30 /usr/share/balloon/src/lib/Bootstrap/Http.php(91): Micro\Http\Router->run()
#31 /usr/share/balloon/bin/httpdocs/index.php(47): Balloon\Bootstrap\Http->process()
#32 {main}
2019-28-08 10:56:01 [Balloon\Filesystem,ERROR]: remove node from result list, failed load node  [object] (Balloon\Filesystem\Exception\NotFound(code: 49): node [5d5f9228b532d8184f47a30a] not found at /usr/share/balloon/src/lib/Filesystem.php:223)
[stacktrace]
#0 /usr/share/balloon/src/lib/Filesystem.php(611): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#1 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, NULL)
#2 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#3 /usr/share/balloon/src/lib/Filesystem.php(220): iterator_to_array(Object(Generator))
#4 /usr/share/balloon/src/lib/Filesystem.php(611): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#5 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, NULL)
#6 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#7 /usr/share/balloon/src/lib/Filesystem.php(220): iterator_to_array(Object(Generator))
#8 /usr/share/balloon/src/lib/Filesystem.php(611): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#9 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, NULL)
#10 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#11 /usr/share/balloon/src/lib/Filesystem.php(220): iterator_to_array(Object(Generator))
#12 /usr/share/balloon/src/lib/Filesystem.php(611): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#13 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, NULL)
#14 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#15 /usr/share/balloon/src/lib/Filesystem.php(220): iterator_to_array(Object(Generator))
#16 /usr/share/balloon/src/lib/Filesystem/Delta.php(441): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#17 /usr/share/balloon/src/lib/Filesystem/Delta.php(300): Balloon\Filesystem\Delta->getDeletedNodeDelta(Array)
#18 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8NTAwfDB...', 100, NULL)
#19 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8NTAwfDB...', 100, NULL)
#20 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8NDAwfDB...', 100, NULL)
#21 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8MzAwfDB...', 100, NULL)
#22 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8MjAwfDB...', 100, NULL)
#23 /usr/share/balloon/src/app/Balloon.App.Api/v1/Node.php(1014): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8MTAwfDB...', 100, NULL)
#24 [internal function]: Balloon\App\Api\v1\Node->getDelta(Object(Balloon\App\Api\v1\AttributeDecorator\DeltaDecorator), NULL, NULL, 'ZGVsdGF8MHwwfDV...', 100, Array)
#25 /usr/share/balloon/vendor/gyselroth/micro-http/src/Router.php(246): call_user_func_array(Array, Array)
#26 /usr/share/balloon/src/lib/Bootstrap/Http.php(91): Micro\Http\Router->run()
#27 /usr/share/balloon/bin/httpdocs/index.php(47): Balloon\Bootstrap\Http->process()
#28 {main}
2019-28-08 10:56:01 [Balloon\Filesystem,ERROR]: remove node from result list, failed load node  [object] (Balloon\Filesystem\Exception\NotFound(code: 49): node [5d5f9250b532d8187244663a] not found at /usr/share/balloon/src/lib/Filesystem.php:223)
[stacktrace]
#0 /usr/share/balloon/src/lib/Filesystem.php(611): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#1 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, NULL)
#2 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#3 /usr/share/balloon/src/lib/Filesystem.php(220): iterator_to_array(Object(Generator))
#4 /usr/share/balloon/src/lib/Filesystem.php(611): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#5 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, NULL)
#6 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#7 /usr/share/balloon/src/lib/Filesystem.php(220): iterator_to_array(Object(Generator))
#8 /usr/share/balloon/src/lib/Filesystem.php(611): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#9 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, NULL)
#10 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#11 /usr/share/balloon/src/lib/Filesystem.php(220): iterator_to_array(Object(Generator))
#12 /usr/share/balloon/src/lib/Filesystem/Delta.php(441): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#13 /usr/share/balloon/src/lib/Filesystem/Delta.php(300): Balloon\Filesystem\Delta->getDeletedNodeDelta(Array)
#14 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8NTAwfDB...', 100, NULL)
#15 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8NTAwfDB...', 100, NULL)
#16 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8NDAwfDB...', 100, NULL)
#17 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8MzAwfDB...', 100, NULL)
#18 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8MjAwfDB...', 100, NULL)
#19 /usr/share/balloon/src/app/Balloon.App.Api/v1/Node.php(1014): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8MTAwfDB...', 100, NULL)
#20 [internal function]: Balloon\App\Api\v1\Node->getDelta(Object(Balloon\App\Api\v1\AttributeDecorator\DeltaDecorator), NULL, NULL, 'ZGVsdGF8MHwwfDV...', 100, Array)
#21 /usr/share/balloon/vendor/gyselroth/micro-http/src/Router.php(246): call_user_func_array(Array, Array)
#22 /usr/share/balloon/src/lib/Bootstrap/Http.php(91): Micro\Http\Router->run()
#23 /usr/share/balloon/bin/httpdocs/index.php(47): Balloon\Bootstrap\Http->process()
#24 {main}
2019-28-08 10:56:01 [Balloon\Filesystem,ERROR]: remove node from result list, failed load node  [object] (Balloon\Filesystem\Exception\NotFound(code: 49): node [5d5f9252b532d815aa17b173] not found at /usr/share/balloon/src/lib/Filesystem.php:223)
[stacktrace]
#0 /usr/share/balloon/src/lib/Filesystem.php(611): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#1 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, NULL)
#2 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#3 /usr/share/balloon/src/lib/Filesystem.php(220): iterator_to_array(Object(Generator))
#4 /usr/share/balloon/src/lib/Filesystem.php(611): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#5 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, NULL)
#6 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#7 /usr/share/balloon/src/lib/Filesystem.php(220): iterator_to_array(Object(Generator))
#8 /usr/share/balloon/src/lib/Filesystem/Delta.php(441): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#9 /usr/share/balloon/src/lib/Filesystem/Delta.php(300): Balloon\Filesystem\Delta->getDeletedNodeDelta(Array)
#10 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8NTAwfDB...', 100, NULL)
#11 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8NTAwfDB...', 100, NULL)
#12 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8NDAwfDB...', 100, NULL)
#13 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8MzAwfDB...', 100, NULL)
#14 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8MjAwfDB...', 100, NULL)
#15 /usr/share/balloon/src/app/Balloon.App.Api/v1/Node.php(1014): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8MTAwfDB...', 100, NULL)
#16 [internal function]: Balloon\App\Api\v1\Node->getDelta(Object(Balloon\App\Api\v1\AttributeDecorator\DeltaDecorator), NULL, NULL, 'ZGVsdGF8MHwwfDV...', 100, Array)
#17 /usr/share/balloon/vendor/gyselroth/micro-http/src/Router.php(246): call_user_func_array(Array, Array)
#18 /usr/share/balloon/src/lib/Bootstrap/Http.php(91): Micro\Http\Router->run()
#19 /usr/share/balloon/bin/httpdocs/index.php(47): Balloon\Bootstrap\Http->process()
#20 {main}
2019-28-08 10:56:01 [Balloon\Filesystem,ERROR]: remove node from result list, failed load node  [object] (Balloon\Filesystem\Exception\NotFound(code: 49): node [5d5f925430101d17ca36facc] not found at /usr/share/balloon/src/lib/Filesystem.php:223)
[stacktrace]
#0 /usr/share/balloon/src/lib/Filesystem.php(611): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#1 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, NULL)
#2 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#13 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, NULL)
#14 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#15 /usr/share/balloon/src/lib/Filesystem.php(220): iterator_to_array(Object(Generator))
#16 /usr/share/balloon/src/lib/Filesystem.php(611): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#17 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, NULL)
#18 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#19 /usr/share/balloon/src/lib/Filesystem.php(220): iterator_to_array(Object(Generator))
#20 /usr/share/balloon/src/lib/Filesystem/Delta.php(240): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId), NULL, 0)
#21 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8Nzg2fDB...', 97, NULL)
#22 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8Nzg2fDB...', 98, NULL)
#23 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8Njg4fDB...', 98, NULL)
#24 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8NTkwfDB...', 98, NULL)
#25 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8NDkyfDB...', 98, NULL)
#26 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8Mzk0fDB...', 98, NULL)
#27 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8Mjk2fDB...', 98, NULL)
#28 /usr/share/balloon/src/lib/Filesystem/Delta.php(313): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8MTk4fDB...', 98, NULL)
#29 /usr/share/balloon/src/app/Balloon.App.Api/v1/Node.php(1014): Balloon\Filesystem\Delta->getDeltaFeed('ZGVsdGF8MTAwfDB...', 100, NULL)
#30 [internal function]: Balloon\App\Api\v1\Node->getDelta(Object(Balloon\App\Api\v1\AttributeDecorator\DeltaDecorator), NULL, NULL, 'ZGVsdGF8MHwwfDV...', 100, Array)
#31 /usr/share/balloon/vendor/gyselroth/micro-http/src/Router.php(246): call_user_func_array(Array, Array)
#32 /usr/share/balloon/src/lib/Bootstrap/Http.php(91): Micro\Http\Router->run()
#33 /usr/share/balloon/bin/httpdocs/index.php(47): Balloon\Bootstrap\Http->process()
#34 {main}
2019-28-08 11:25:29 [Balloon\Filesystem,ERROR]: remove node from result list, failed load node  [object] (Balloon\Filesystem\Exception\NotFound(code: 49): node [5d5f9228b532d8184f47a30a] not found at /usr/share/balloon/src/lib/Filesystem.php:223)
[stacktrace]
#2 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
#3 /usr/share/balloon/src/lib/Filesystem.php(220): iterator_to_array(Object(Generator))
#39 {main}
2019-28-08 11:59:43 [Balloon\Filesystem,ERROR]: remove node from result list, failed load node  [object] (Balloon\Filesystem\Exception\NotFound(code: 49): node [5d5f91f930101d16bf550ef2] not found at /usr/share/balloon/src/lib/Filesystem.php:223)
[stacktrace]
#0 /usr/share/balloon/src/lib/Filesystem.php(611): Balloon\Filesystem->findNodeById(Object(MongoDB\BSON\ObjectId))
#1 /usr/share/balloon/src/lib/Filesystem.php(763): Balloon\Filesystem->initNode(Array, NULL)
#2 [internal function]: Balloon\Filesystem->executeAggregation(Array, 0, 1, NULL)
```

**Comment by raffis** [comment]
Nodes forbidden by access control were not stored in the internal node cache. Therefore in the context of an inbox share where other inbox share members do not have access to such nodes were all parent nodes loaded for each node which led to huge timeouts.
